Manchester-Central/2025-Reefscape

- simgui-ds.json
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/SimpleDriveToPosition.java
- src/main/java/frc/robot/utils/FieldPoint.java
- src/test/java/frc/robot/utils/FieldPointTests.java
> added drivetoposition command

- .gitignore
- build.gradle
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/SwerveDrive.java
> Drive to position path planner

- build.gradle
- src/main/java/frc/robot/RobotContainer.java
> Made m_swerveDrive SwerveDrive type

- .gitignore
- build.gradle
- src/main/java/frc/robot/Robot.java
build constands showing data everytime we build
> Build constants

- documents/State-Machines/Gripper-State-Machine-Diagram.drawio
- documents/State-Machines/Intake-State-Machine-Diagram.drawio
- documents/State-Machines/Lift-State-Machine-Diagram.drawio
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/Gripper.java
- src/main/java/frc/robot/subsystems/Intake.java
- src/main/java/frc/robot/subsystems/Lift.java
- src/main/java/frc/robot/subsystems/shared/ISubsystemState.java
- src/main/java/frc/robot/subsystems/shared/StateBasedSubsystem.java
Initial code for State Machine-based subsystems
> State machines

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/lift/BasePivot.java
- src/main/java/frc/robot/subsystems/lift/Extender.java
- src/main/java/frc/robot/subsystems/lift/Gripper.java
- src/main/java/frc/robot/subsystems/lift/GripperPivot.java
- src/main/java/frc/robot/utils/ChaosTalonFx.java
To review during the meeting tonight. And to have the students implement for the other 3 parts of the IdLift
> Adds ChaosTalonFx and sample BasePivot control

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/Intake.java
- src/main/java/frc/robot/subsystems/Mech2DManager.java
- src/main/java/frc/robot/subsystems/SwerveDrive.java
- src/main/java/frc/robot/subsystems/SwerveModule2025.java
- src/main/java/frc/robot/subsystems/lift/IdLift.java
Added the Intake to the Sim, refactored swerve constants, flipped lift in the sim
> Saturday 2/1 Morning

- .vscode/settings.json
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/subsystems/lift/BasePivot.java
- src/main/java/frc/robot/subsystems/lift/Extender.java
- src/main/java/frc/robot/subsystems/lift/GripperPivot.java
- src/main/java/frc/robot/subsystems/lift/IdLift.java
- src/main/java/frc/robot/subsystems/lift/LiftPose.java
Adds some extra stuff to help with lift tuning:
- Lift Poses with dashboard update support
- scoreHelper to handle shared scoring pose logic
- limiting speeds and target values for lift parts
> Lift tuning prep

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/subsystems/Intake.java
- src/main/java/frc/robot/subsystems/lift/BasePivot.java
- src/main/java/frc/robot/subsystems/lift/Extender.java
- src/main/java/frc/robot/subsystems/lift/GripperPivot.java
- src/main/java/frc/robot/utils/ChaosCanCoder.java
- src/main/java/frc/robot/utils/ChaosCanCoderTuner.java
- src/main/java/frc/robot/utils/ChaosTalonFx.java
> Lift bring up prep

- src/main/deploy/pathplanner/autos/Blue1-HPIntake1.auto
- src/main/deploy/pathplanner/autos/Blue1-Reef11ScoreL4.auto
- src/main/deploy/pathplanner/paths/Blue1-HPIntake.path
- src/main/deploy/pathplanner/paths/Blue1-Reef11.path
- src/main/deploy/pathplanner/paths/Blue1-Reef6ScoreL4.path
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/WaitForState.java
- src/main/java/frc/robot/subsystems/Intake.java
- src/main/java/frc/robot/subsystems/lift/Gripper.java
- src/main/java/frc/robot/subsystems/lift/IdLift.java
- src/main/java/frc/robot/subsystems/shared/StateBasedSubsystem.java
After John (-John) and I created a Coral Reef auto on L4, I created a HP Auto but haven't linked the two autos together yet
> Auto attempt

- build.gradle
- src/main/deploy/pathplanner/settings.json
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/DriverRelativeDrive.java
- src/main/java/frc/robot/subsystems/SwerveDrive.java
> Pathplanner fixes

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/DriverRelativeSetAngleDrive.java
- src/main/java/frc/robot/subsystems/lift/Extender.java
- src/main/java/frc/robot/subsystems/lift/GripperPivot.java
- src/main/java/frc/robot/subsystems/lift/IdLift.java
- src/main/java/frc/robot/utils/FieldPoint.java
Hey Josh when you are alive, plz look at this. We hope you are having fun🤖
> Tuning score values

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/subsystems/Camera.java
AAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHH
> L3 and L2 poseses might be finale or not 🤷‍♂️

- build.gradle
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/SimConstants.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/GripperPivot.java
* Checkstyle fixes
* Some arm states fixes
* Gripper Pivot fixing error with kI
* Checkstyle doesn't open if you have no errors
> Minor fixes before 3/16

- src/main/deploy/pathplanner/autos/Intake from floor test.auto
- src/main/deploy/pathplanner/autos/scoreL4.auto
- src/main/deploy/pathplanner/paths/10L-M1.path
- src/main/deploy/pathplanner/paths/10R-M1.path
- src/main/deploy/pathplanner/paths/8L-M1.path
- src/main/deploy/pathplanner/paths/8L-M2.path
- src/main/deploy/pathplanner/paths/8R-M1.path
- src/main/deploy/pathplanner/paths/8R-M2.path
- src/main/deploy/pathplanner/paths/Drive2MetersForward.path
- src/main/deploy/pathplanner/paths/Test Path.path
- src/main/deploy/pathplanner/paths/intake from floor test.path
- src/main/deploy/pathplanner/settings.json
(Creating a PR for Isaac to push his auto changes into)
> Isaac's Autos for Week 4

- config/checkstyle/checkstyle.xml
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/LimelightHelpers.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/AlignReefTag.java
- src/main/java/frc/robot/commands/ReefAlignment.java
- src/main/java/frc/robot/commands/SimpleDriveToPositionV2.java
- src/main/java/frc/robot/subsystems/MechManager2D.java
- src/main/java/frc/robot/subsystems/SwerveDrive.java
- src/main/java/frc/robot/subsystems/SwerveModule2025.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/ArmPose.java
- src/main/java/frc/robot/subsystems/arm/BasePivot.java
- src/main/java/frc/robot/subsystems/arm/Extender.java
- src/main/java/frc/robot/subsystems/arm/GripperPivot.java
- src/main/java/frc/robot/utils/FieldPoint.java
started to integrate the units library in the code
> Update to units library

- src/main/deploy/pathplanner/paths/Circle Test.path
- src/main/deploy/pathplanner/paths/Paths that look like Balloon Animals.path
- src/main/deploy/pathplanner/paths/Paths with reef in sight.path
- src/main/deploy/pathplanner/paths/Paths with reef out of sight.path
- src/main/deploy/pathplanner/paths/Paths with spins in them.path
- src/main/deploy/pathplanner/paths/Triangle Test Path.path
> Adding Generated test paths

- .gitignore
- documents/State-Machines/State Machine Diagram for CRAG.drawio
> ADDED COLOR TO DIAGRAM!!!!

- src/main/deploy/pathplanner/autos/Sweep 6R-6L LOL.auto
- src/main/deploy/pathplanner/paths/6R-M2.path
- src/main/deploy/pathplanner/paths/Left1 -sweep-6R.path
This seems to be some auto changes that @NinjaBuilderPro made during elims on saturday.
> DCMP Saturday

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/commands/Xmode.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/utils/FieldPoint.java
> Added control updates for battlcry(Needs testing, pose needs tuning)
